[package]
name = "whattheframe"
version = "0.1.0"
edition = "2018"

[dependencies]
gtk4 = { git = "https://github.com/gtk-rs/gtk4-rs" }
serde = { version = "1.0", features = ["derive"] }
bincode = "1.3"
