[package]
name = "wtf"
version = "0.1.0"
edition = "2018"

[dependencies]
once_cell = "1.7"
parking_lot = "0.11"
flume = "0.10"
bincode = "1.3"
serde = { version = "1.0", features = ["derive"] }
snap = "1.0"
